[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["node_modules", "lib"]
optimizer = true
solc_version = "0.8.27"
via_ir = true
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@chainlink/=node_modules/@chainlink/',
    '@aave/=node_modules/@aave/',
    'forge-std/=lib/forge-std/src/'
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
